// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccessRuleRole.
const (
	AccessRuleRoleAdmin        AccessRuleRole = "admin"
	AccessRuleRoleProgramAdmin AccessRuleRole = "program-admin"
	AccessRuleRoleViewer       AccessRuleRole = "viewer"
)

// Defines values for Gender.
const (
	GenderFemale Gender = "female"
	GenderMale   Gender = "male"
)

// Defines values for HousingRoomSpecBathroom.
const (
	HousingRoomSpecBathroomPrivate HousingRoomSpecBathroom = "private"
	HousingRoomSpecBathroomShared  HousingRoomSpecBathroom = "shared"
)

// Defines values for ScopeType.
const (
	ScopeTypeCamp   ScopeType = "camp"
	ScopeTypeSystem ScopeType = "system"
	ScopeTypeTenant ScopeType = "tenant"
)

// Defines values for AreasSortBy.
const (
	AreasSortByName AreasSortBy = "name"
)

// Defines values for CampersSortBy.
const (
	CampersSortByBirthday       CampersSortBy = "birthday"
	CampersSortByGender         CampersSortBy = "gender"
	CampersSortByHousingGroupId CampersSortBy = "housingGroupId"
	CampersSortByName           CampersSortBy = "name"
	CampersSortBySessionId      CampersSortBy = "sessionId"
)

// Defines values for CampsSortBy.
const (
	CampsSortByName CampsSortBy = "name"
)

// Defines values for CertificationsSortBy.
const (
	CertificationsSortByName CertificationsSortBy = "name"
)

// Defines values for ColorsSortBy.
const (
	ColorsSortByHexCode ColorsSortBy = "hexCode"
	ColorsSortByName    ColorsSortBy = "name"
)

// Defines values for GroupsSortBy.
const (
	GroupsSortByHousingRoomId GroupsSortBy = "housingRoomId"
	GroupsSortByName          GroupsSortBy = "name"
	GroupsSortBySessionId     GroupsSortBy = "sessionId"
)

// Defines values for HousingRoomsSortBy.
const (
	HousingRoomsSortByCapacity HousingRoomsSortBy = "capacity"
	HousingRoomsSortByName     HousingRoomsSortBy = "name"
)

// Defines values for LocationsSortBy.
const (
	LocationsSortByAreaId LocationsSortBy = "areaId"
	LocationsSortByName   LocationsSortBy = "name"
)

// Defines values for RolesSortBy.
const (
	RolesSortByName RolesSortBy = "name"
)

// Defines values for SessionsSortBy.
const (
	SessionsSortByEndDate   SessionsSortBy = "endDate"
	SessionsSortByName      SessionsSortBy = "name"
	SessionsSortByStartDate SessionsSortBy = "startDate"
)

// Defines values for StaffMembersSortBy.
const (
	StaffMembersSortByCertificationId StaffMembersSortBy = "certificationId"
	StaffMembersSortByGender          StaffMembersSortBy = "gender"
	StaffMembersSortByName            StaffMembersSortBy = "name"
	StaffMembersSortByPhone           StaffMembersSortBy = "phone"
	StaffMembersSortByRoleId          StaffMembersSortBy = "roleId"
)

// Defines values for SortOrder.
const (
	SortOrderAsc  SortOrder = "asc"
	SortOrderDesc SortOrder = "desc"
)

// Defines values for GetCampsParamsSortBy.
const (
	GetCampsParamsSortByName GetCampsParamsSortBy = "name"
)

// Defines values for GetCampsParamsSortOrder.
const (
	GetCampsParamsSortOrderAsc  GetCampsParamsSortOrder = "asc"
	GetCampsParamsSortOrderDesc GetCampsParamsSortOrder = "desc"
)

// Defines values for ListAreasParamsSortBy.
const (
	ListAreasParamsSortByName ListAreasParamsSortBy = "name"
)

// Defines values for ListAreasParamsSortOrder.
const (
	ListAreasParamsSortOrderAsc  ListAreasParamsSortOrder = "asc"
	ListAreasParamsSortOrderDesc ListAreasParamsSortOrder = "desc"
)

// Defines values for ListCampersParamsSortBy.
const (
	ListCampersParamsSortByBirthday       ListCampersParamsSortBy = "birthday"
	ListCampersParamsSortByGender         ListCampersParamsSortBy = "gender"
	ListCampersParamsSortByHousingGroupId ListCampersParamsSortBy = "housingGroupId"
	ListCampersParamsSortByName           ListCampersParamsSortBy = "name"
	ListCampersParamsSortBySessionId      ListCampersParamsSortBy = "sessionId"
)

// Defines values for ListCampersParamsSortOrder.
const (
	ListCampersParamsSortOrderAsc  ListCampersParamsSortOrder = "asc"
	ListCampersParamsSortOrderDesc ListCampersParamsSortOrder = "desc"
)

// Defines values for ListCertificationsParamsSortBy.
const (
	ListCertificationsParamsSortByName ListCertificationsParamsSortBy = "name"
)

// Defines values for ListCertificationsParamsSortOrder.
const (
	ListCertificationsParamsSortOrderAsc  ListCertificationsParamsSortOrder = "asc"
	ListCertificationsParamsSortOrderDesc ListCertificationsParamsSortOrder = "desc"
)

// Defines values for ListColorsParamsSortBy.
const (
	ListColorsParamsSortByHexCode ListColorsParamsSortBy = "hexCode"
	ListColorsParamsSortByName    ListColorsParamsSortBy = "name"
)

// Defines values for ListColorsParamsSortOrder.
const (
	ListColorsParamsSortOrderAsc  ListColorsParamsSortOrder = "asc"
	ListColorsParamsSortOrderDesc ListColorsParamsSortOrder = "desc"
)

// Defines values for ListGroupsParamsSortBy.
const (
	ListGroupsParamsSortByHousingRoomId ListGroupsParamsSortBy = "housingRoomId"
	ListGroupsParamsSortByName          ListGroupsParamsSortBy = "name"
	ListGroupsParamsSortBySessionId     ListGroupsParamsSortBy = "sessionId"
)

// Defines values for ListGroupsParamsSortOrder.
const (
	ListGroupsParamsSortOrderAsc  ListGroupsParamsSortOrder = "asc"
	ListGroupsParamsSortOrderDesc ListGroupsParamsSortOrder = "desc"
)

// Defines values for ListHousingRoomsParamsSortBy.
const (
	ListHousingRoomsParamsSortByCapacity ListHousingRoomsParamsSortBy = "capacity"
	ListHousingRoomsParamsSortByName     ListHousingRoomsParamsSortBy = "name"
)

// Defines values for ListHousingRoomsParamsSortOrder.
const (
	ListHousingRoomsParamsSortOrderAsc  ListHousingRoomsParamsSortOrder = "asc"
	ListHousingRoomsParamsSortOrderDesc ListHousingRoomsParamsSortOrder = "desc"
)

// Defines values for ListLocationsParamsSortBy.
const (
	ListLocationsParamsSortByAreaId ListLocationsParamsSortBy = "areaId"
	ListLocationsParamsSortByName   ListLocationsParamsSortBy = "name"
)

// Defines values for ListLocationsParamsSortOrder.
const (
	ListLocationsParamsSortOrderAsc  ListLocationsParamsSortOrder = "asc"
	ListLocationsParamsSortOrderDesc ListLocationsParamsSortOrder = "desc"
)

// Defines values for ListRolesParamsSortBy.
const (
	ListRolesParamsSortByName ListRolesParamsSortBy = "name"
)

// Defines values for ListRolesParamsSortOrder.
const (
	ListRolesParamsSortOrderAsc  ListRolesParamsSortOrder = "asc"
	ListRolesParamsSortOrderDesc ListRolesParamsSortOrder = "desc"
)

// Defines values for ListSessionsParamsSortBy.
const (
	ListSessionsParamsSortByEndDate   ListSessionsParamsSortBy = "endDate"
	ListSessionsParamsSortByName      ListSessionsParamsSortBy = "name"
	ListSessionsParamsSortByStartDate ListSessionsParamsSortBy = "startDate"
)

// Defines values for ListSessionsParamsSortOrder.
const (
	ListSessionsParamsSortOrderAsc  ListSessionsParamsSortOrder = "asc"
	ListSessionsParamsSortOrderDesc ListSessionsParamsSortOrder = "desc"
)

// Defines values for ListStaffMembersParamsSortBy.
const (
	ListStaffMembersParamsSortByCertificationId ListStaffMembersParamsSortBy = "certificationId"
	ListStaffMembersParamsSortByGender          ListStaffMembersParamsSortBy = "gender"
	ListStaffMembersParamsSortByName            ListStaffMembersParamsSortBy = "name"
	ListStaffMembersParamsSortByPhone           ListStaffMembersParamsSortBy = "phone"
	ListStaffMembersParamsSortByRoleId          ListStaffMembersParamsSortBy = "roleId"
)

// Defines values for ListStaffMembersParamsSortOrder.
const (
	ListStaffMembersParamsSortOrderAsc  ListStaffMembersParamsSortOrder = "asc"
	ListStaffMembersParamsSortOrderDesc ListStaffMembersParamsSortOrder = "desc"
)

// AccessRule defines model for AccessRule.
type AccessRule struct {
	Role AccessRuleRole `json:"role"`

	// ScopeId The unique identifier of the tenant or camp according to the scope type (null for system)
	ScopeId *string `json:"scopeId"`

	// ScopeType The scope level for an access rule
	ScopeType ScopeType `json:"scopeType"`
}

// AccessRuleRole defines model for AccessRule.Role.
type AccessRuleRole string

// ActivitiesListResponse defines model for ActivitiesListResponse.
type ActivitiesListResponse struct {
	Items []Activity `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// Activity defines model for Activity.
type Activity struct {
	Meta EntityMeta   `json:"meta"`
	Spec ActivitySpec `json:"spec"`
}

// ActivityCreationRequest defines model for ActivityCreationRequest.
type ActivityCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec ActivitySpec              `json:"spec"`
}

// ActivitySpec defines model for ActivitySpec.
type ActivitySpec struct {
	// DefaultLocationId ID of the default location
	DefaultLocationId *openapi_types.UUID `json:"defaultLocationId,omitempty"`

	// Duration Default duration in minutes (mutually exclusive with fixedTime)
	Duration *int `json:"duration,omitempty"`

	// FixedTime Fixed time for the activity (mutually exclusive with duration)
	FixedTime *struct {
		// EndTime End time for the activity
		EndTime string `json:"endTime"`

		// StartTime Start time for the activity
		StartTime string `json:"startTime"`
	} `json:"fixedTime,omitempty"`

	// ProgramId ID of the program this activity belongs to
	ProgramId     openapi_types.UUID `json:"programId"`
	RequiredStaff *[]struct {
		// PositionName Name of the position required for this activity
		PositionName string `json:"positionName"`

		// RequiredCertificationId ID of the certification required for this position
		RequiredCertificationId *openapi_types.UUID `json:"requiredCertificationId,omitempty"`
	} `json:"requiredStaff,omitempty"`
}

// ActivityUpdateRequest defines model for ActivityUpdateRequest.
type ActivityUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec ActivitySpec              `json:"spec"`
}

// Area defines model for Area.
type Area struct {
	Meta EntityMeta `json:"meta"`
	Spec AreaSpec   `json:"spec"`
}

// AreaCreationRequest defines model for AreaCreationRequest.
type AreaCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec AreaSpec                  `json:"spec"`
}

// AreaSpec defines model for AreaSpec.
type AreaSpec struct {
	Capacity  *int      `json:"capacity,omitempty"`
	Equipment *[]string `json:"equipment,omitempty"`
	Notes     *string   `json:"notes,omitempty"`
}

// AreaUpdateRequest defines model for AreaUpdateRequest.
type AreaUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec AreaSpec                  `json:"spec"`
}

// AreasListResponse defines model for AreasListResponse.
type AreasListResponse struct {
	Items []Area `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// AuthMe defines model for AuthMe.
type AuthMe struct {
	User User `json:"user"`
}

// Birthday Date of birth of the camper or staff member
type Birthday = openapi_types.Date

// Camp defines model for Camp.
type Camp struct {
	Meta struct {
		// CreatedAt The date and time the camp was created
		CreatedAt time.Time `json:"createdAt"`

		// Description The description of the camp
		Description *string `json:"description,omitempty"`

		// Id The unique identifier of the camp
		Id openapi_types.UUID `json:"id"`

		// Name The name of the camp
		Name string `json:"name"`

		// TenantId The unique identifier of the tenant that owns the camp
		TenantId openapi_types.UUID `json:"tenantId"`

		// UpdatedAt The date and time the camp was last updated
		UpdatedAt time.Time `json:"updatedAt"`
	} `json:"meta"`
	Spec CampSpec `json:"spec"`
}

// CampCreationRequest defines model for CampCreationRequest.
type CampCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec CampSpec                  `json:"spec"`
}

// CampSpec defines model for CampSpec.
type CampSpec struct {
	Address *struct {
		City    *string `json:"city,omitempty"`
		Country *string `json:"country,omitempty"`
		State   *string `json:"state,omitempty"`
		Street  *string `json:"street,omitempty"`
		ZipCode *string `json:"zipCode,omitempty"`
	} `json:"address,omitempty"`
	ContactInfo *struct {
		Email   *openapi_types.Email `json:"email,omitempty"`
		Phone   *string              `json:"phone,omitempty"`
		Website *string              `json:"website,omitempty"`
	} `json:"contactInfo,omitempty"`

	// DailyEndTime Daily end time for calendar display (24-hour format HH:MM)
	DailyEndTime string `json:"dailyEndTime"`

	// DailyStartTime Daily start time for calendar display (24-hour format HH:MM)
	DailyStartTime string `json:"dailyStartTime"`

	// EndDate Overall camp season end date
	EndDate openapi_types.Date `json:"endDate"`
	LogoUrl *string            `json:"logoUrl,omitempty"`

	// StartDate Overall camp season start date
	StartDate openapi_types.Date `json:"startDate"`
}

// CampUpdateRequest defines model for CampUpdateRequest.
type CampUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec CampSpec                  `json:"spec"`
}

// Camper defines model for Camper.
type Camper struct {
	Meta EntityMeta `json:"meta"`
	Spec CamperSpec `json:"spec"`
}

// CamperCreationRequest defines model for CamperCreationRequest.
type CamperCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec CamperMutationSpec        `json:"spec"`
}

// CamperMutationSpec defines model for CamperMutationSpec.
type CamperMutationSpec struct {
	// Birthday Date of birth of the camper or staff member
	Birthday Birthday `json:"birthday"`

	// Gender Gender of the camper or staff member
	Gender Gender `json:"gender"`

	// GroupIds IDs of the groups this camper belongs to (max one housing group allowed)
	GroupIds *[]openapi_types.UUID `json:"groupIds,omitempty"`

	// SessionId ID of the camp session this camper is registered in
	SessionId openapi_types.UUID `json:"sessionId"`
}

// CamperSpec defines model for CamperSpec.
type CamperSpec struct {
	// Birthday Date of birth of the camper or staff member
	Birthday Birthday `json:"birthday"`

	// Gender Gender of the camper or staff member
	Gender Gender `json:"gender"`

	// GroupIds IDs of the groups this camper belongs to
	GroupIds *[]openapi_types.UUID `json:"groupIds,omitempty"`

	// HousingGroupId ID of the housing group this camper belongs to (auto-populated from groupIds)
	HousingGroupId *openapi_types.UUID `json:"housingGroupId,omitempty"`

	// SessionId ID of the camp session this camper is registered in
	SessionId openapi_types.UUID `json:"sessionId"`
}

// CamperUpdateRequest defines model for CamperUpdateRequest.
type CamperUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec CamperMutationSpec        `json:"spec"`
}

// CampersListResponse defines model for CampersListResponse.
type CampersListResponse struct {
	Items []Camper `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// CampsListResponse defines model for CampsListResponse.
type CampsListResponse struct {
	Items []Camp `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// Certification defines model for Certification.
type Certification struct {
	Meta EntityMeta        `json:"meta"`
	Spec CertificationSpec `json:"spec"`
}

// CertificationCreationRequest defines model for CertificationCreationRequest.
type CertificationCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec CertificationSpec         `json:"spec"`
}

// CertificationSpec defines model for CertificationSpec.
type CertificationSpec = map[string]interface{}

// CertificationUpdateRequest defines model for CertificationUpdateRequest.
type CertificationUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec CertificationSpec         `json:"spec"`
}

// CertificationsListResponse defines model for CertificationsListResponse.
type CertificationsListResponse struct {
	Items []Certification `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// Color defines model for Color.
type Color struct {
	Meta EntityMeta `json:"meta"`
	Spec ColorSpec  `json:"spec"`
}

// ColorCreationRequest defines model for ColorCreationRequest.
type ColorCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec ColorSpec                 `json:"spec"`
}

// ColorSpec defines model for ColorSpec.
type ColorSpec struct {
	// Default Whether this is the default color for events
	Default *bool `json:"default,omitempty"`

	// HexValue Hex color value (e.g., "#FF5733")
	HexValue string `json:"hexValue"`
}

// ColorUpdateRequest defines model for ColorUpdateRequest.
type ColorUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec ColorSpec                 `json:"spec"`
}

// ColorsListResponse defines model for ColorsListResponse.
type ColorsListResponse struct {
	Items []Color `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// DurationPreset defines model for DurationPreset.
type DurationPreset struct {
	Meta EntityMeta         `json:"meta"`
	Spec DurationPresetSpec `json:"spec"`
}

// DurationPresetCreationRequest defines model for DurationPresetCreationRequest.
type DurationPresetCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec DurationPresetSpec        `json:"spec"`
}

// DurationPresetSpec defines model for DurationPresetSpec.
type DurationPresetSpec struct {
	// Default Whether this is the default duration preset
	Default *bool `json:"default,omitempty"`

	// DurationMinutes Duration in minutes
	DurationMinutes int `json:"durationMinutes"`
}

// DurationPresetUpdateRequest defines model for DurationPresetUpdateRequest.
type DurationPresetUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec DurationPresetSpec        `json:"spec"`
}

// EntityCreationRequestMeta defines model for EntityCreationRequestMeta.
type EntityCreationRequestMeta struct {
	// Description Description of the entity
	Description *string `json:"description,omitempty"`

	// Name Name of the entity
	Name string `json:"name"`
}

// EntityMeta defines model for EntityMeta.
type EntityMeta struct {
	// CampId The unique identifier of the camp this entity belongs to
	CampId openapi_types.UUID `json:"campId"`

	// CreatedAt The date and time the entity was created
	CreatedAt time.Time `json:"createdAt"`

	// Description The description of the entity
	Description *string `json:"description,omitempty"`

	// Id The unique identifier of the entity
	Id openapi_types.UUID `json:"id"`

	// Name The name of the entity
	Name string `json:"name"`

	// TenantId The unique identifier of the tenant this entity belongs to
	TenantId openapi_types.UUID `json:"tenantId"`

	// UpdatedAt The date and time the entity was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// Event defines model for Event.
type Event struct {
	Meta EntityMeta `json:"meta"`
	Spec EventSpec  `json:"spec"`
}

// EventCreationRequest defines model for EventCreationRequest.
type EventCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec EventSpec                 `json:"spec"`
}

// EventSpec defines model for EventSpec.
type EventSpec struct {
	ActivityId *openapi_types.UUID `json:"activityId,omitempty"`
	Capacity   *int                `json:"capacity,omitempty"`
	ColorId    *openapi_types.UUID `json:"colorId,omitempty"`
	EndDate    time.Time           `json:"endDate"`

	// ExcludeCamperIds IDs of campers to exclude from assigned groups
	ExcludeCamperIds *[]openapi_types.UUID `json:"excludeCamperIds,omitempty"`

	// ExcludeStaffIds IDs of staff members to exclude from assigned groups
	ExcludeStaffIds *[]openapi_types.UUID `json:"excludeStaffIds,omitempty"`

	// GroupIds IDs of groups assigned to this event
	GroupIds *[]openapi_types.UUID `json:"groupIds,omitempty"`

	// IsRecurrenceParent Indicates if this is the parent event of a recurrence series
	IsRecurrenceParent *bool               `json:"isRecurrenceParent,omitempty"`
	LocationId         *openapi_types.UUID `json:"locationId,omitempty"`
	ProgramId          *openapi_types.UUID `json:"programId,omitempty"`

	// RecurrenceId Recurrence rule ID - links this event to a recurrence series
	RecurrenceId  *openapi_types.UUID `json:"recurrenceId,omitempty"`
	RequiredStaff *[]struct {
		// AssignedStaffId ID of the staff member assigned to this position
		AssignedStaffId *openapi_types.UUID `json:"assignedStaffId,omitempty"`

		// PositionName Name of the position required for this event
		PositionName string `json:"positionName"`

		// RequiredCertificationId ID of the certification required for this position
		RequiredCertificationId *openapi_types.UUID `json:"requiredCertificationId,omitempty"`
	} `json:"requiredStaff,omitempty"`
	StartDate time.Time `json:"startDate"`
}

// EventUpdateRequest defines model for EventUpdateRequest.
type EventUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec EventSpec                 `json:"spec"`
}

// EventsListResponse defines model for EventsListResponse.
type EventsListResponse struct {
	Items []Event `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// Gender Gender of the camper or staff member
type Gender string

// Group defines model for Group.
type Group struct {
	Meta EntityMeta `json:"meta"`
	Spec GroupSpec  `json:"spec"`
}

// GroupCreationRequest defines model for GroupCreationRequest.
type GroupCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec GroupSpec                 `json:"spec"`
}

// GroupSpec defines model for GroupSpec.
type GroupSpec struct {
	// CamperIds Manually selected camper IDs (cannot be used with groupIds)
	CamperIds *[]openapi_types.UUID `json:"camperIds,omitempty"`

	// GroupIds Child group IDs for creating nested groups (cannot be used with camperIds or staffIds)
	GroupIds *[]openapi_types.UUID `json:"groupIds,omitempty"`

	// HousingRoomId Optional housing room assignment for this group
	HousingRoomId *openapi_types.UUID `json:"housingRoomId,omitempty"`

	// SessionId Optional session this group belongs to
	SessionId *openapi_types.UUID `json:"sessionId,omitempty"`

	// StaffIds Manually selected staff IDs (cannot be used with groupIds)
	StaffIds *[]openapi_types.UUID `json:"staffIds,omitempty"`
}

// GroupUpdateRequest defines model for GroupUpdateRequest.
type GroupUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec GroupSpec                 `json:"spec"`
}

// GroupsListResponse defines model for GroupsListResponse.
type GroupsListResponse struct {
	Items []Group `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// HousingRoom defines model for HousingRoom.
type HousingRoom struct {
	Meta EntityMeta      `json:"meta"`
	Spec HousingRoomSpec `json:"spec"`
}

// HousingRoomCreationRequest defines model for HousingRoomCreationRequest.
type HousingRoomCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec HousingRoomSpec           `json:"spec"`
}

// HousingRoomSpec defines model for HousingRoomSpec.
type HousingRoomSpec struct {
	// AreaId ID of the physical area where this housing room is located
	AreaId *openapi_types.UUID `json:"areaId,omitempty"`

	// Bathroom Type of bathroom for this housing room
	Bathroom *HousingRoomSpecBathroom `json:"bathroom,omitempty"`

	// Beds Number of beds in this housing room
	Beds int `json:"beds"`
}

// HousingRoomSpecBathroom Type of bathroom for this housing room
type HousingRoomSpecBathroom string

// HousingRoomUpdateRequest defines model for HousingRoomUpdateRequest.
type HousingRoomUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec HousingRoomSpec           `json:"spec"`
}

// HousingRoomsListResponse defines model for HousingRoomsListResponse.
type HousingRoomsListResponse struct {
	Items []HousingRoom `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// ListResponseBase defines model for ListResponseBase.
type ListResponseBase struct {
	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// Location defines model for Location.
type Location struct {
	Meta EntityMeta   `json:"meta"`
	Spec LocationSpec `json:"spec"`
}

// LocationCreationRequest defines model for LocationCreationRequest.
type LocationCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec LocationSpec              `json:"spec"`
}

// LocationSpec defines model for LocationSpec.
type LocationSpec struct {
	// AreaId ID of the physical area where this location is situated
	AreaId    *openapi_types.UUID `json:"areaId,omitempty"`
	Capacity  *int                `json:"capacity,omitempty"`
	Equipment *[]string           `json:"equipment,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
}

// LocationUpdateRequest defines model for LocationUpdateRequest.
type LocationUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec LocationSpec              `json:"spec"`
}

// LocationsListResponse defines model for LocationsListResponse.
type LocationsListResponse struct {
	Items []Location `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Password User's password
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token Authentication token (placeholder for future implementation)
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Program defines model for Program.
type Program struct {
	Meta EntityMeta  `json:"meta"`
	Spec ProgramSpec `json:"spec"`
}

// ProgramCreationRequest defines model for ProgramCreationRequest.
type ProgramCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec ProgramSpec               `json:"spec"`
}

// ProgramSpec defines model for ProgramSpec.
type ProgramSpec struct {
	// ActivityIds Activities belonging to this program
	ActivityIds *[]openapi_types.UUID `json:"activityIds,omitempty"`
	ColorId     *openapi_types.UUID   `json:"colorId,omitempty"`

	// LocationIds Locations associated with this program
	LocationIds *[]openapi_types.UUID `json:"locationIds,omitempty"`

	// StaffGroupIds Staff groups associated with this program
	StaffGroupIds *[]openapi_types.UUID `json:"staffGroupIds,omitempty"`
}

// ProgramUpdateRequest defines model for ProgramUpdateRequest.
type ProgramUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec ProgramSpec               `json:"spec"`
}

// ProgramsListResponse defines model for ProgramsListResponse.
type ProgramsListResponse struct {
	Items []Program `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// Role defines model for Role.
type Role struct {
	Meta EntityMeta `json:"meta"`
	Spec RoleSpec   `json:"spec"`
}

// RoleCreationRequest defines model for RoleCreationRequest.
type RoleCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec RoleSpec                  `json:"spec"`
}

// RoleSpec defines model for RoleSpec.
type RoleSpec = map[string]interface{}

// RoleUpdateRequest defines model for RoleUpdateRequest.
type RoleUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec RoleSpec                  `json:"spec"`
}

// RolesListResponse defines model for RolesListResponse.
type RolesListResponse struct {
	Items []Role `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// ScopeType The scope level for an access rule
type ScopeType string

// Session defines model for Session.
type Session struct {
	Meta EntityMeta  `json:"meta"`
	Spec SessionSpec `json:"spec"`
}

// SessionCreationRequest defines model for SessionCreationRequest.
type SessionCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec SessionSpec               `json:"spec"`
}

// SessionSpec defines model for SessionSpec.
type SessionSpec struct {
	EndDate   openapi_types.Date `json:"endDate"`
	StartDate openapi_types.Date `json:"startDate"`
}

// SessionUpdateRequest defines model for SessionUpdateRequest.
type SessionUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec SessionSpec               `json:"spec"`
}

// SessionsListResponse defines model for SessionsListResponse.
type SessionsListResponse struct {
	Items []Session `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Password User's password
	Password string `json:"password"`

	// TenantId The tenant this user will belong to
	TenantId string `json:"tenantId"`
}

// StaffMember defines model for StaffMember.
type StaffMember struct {
	Meta EntityMeta      `json:"meta"`
	Spec StaffMemberSpec `json:"spec"`
}

// StaffMemberCreationRequest defines model for StaffMemberCreationRequest.
type StaffMemberCreationRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec StaffMemberMutationSpec   `json:"spec"`
}

// StaffMemberMutationSpec defines model for StaffMemberMutationSpec.
type StaffMemberMutationSpec struct {
	// Birthday Date of birth of the camper or staff member
	Birthday Birthday `json:"birthday"`

	// CertificationIds IDs of certifications this staff member holds
	CertificationIds *[]openapi_types.UUID `json:"certificationIds,omitempty"`

	// Gender Gender of the camper or staff member
	Gender Gender `json:"gender"`

	// GroupIds IDs of the groups this staff member belongs to (max one housing group allowed)
	GroupIds *[]openapi_types.UUID `json:"groupIds,omitempty"`
	Phone    *string               `json:"phone,omitempty"`

	// RoleId ID of the role this staff member has
	RoleId openapi_types.UUID `json:"roleId"`
}

// StaffMemberSpec defines model for StaffMemberSpec.
type StaffMemberSpec struct {
	// Birthday Date of birth of the camper or staff member
	Birthday Birthday `json:"birthday"`

	// CertificationIds IDs of certifications this staff member holds
	CertificationIds *[]openapi_types.UUID `json:"certificationIds,omitempty"`

	// Gender Gender of the camper or staff member
	Gender Gender `json:"gender"`

	// GroupIds IDs of the groups this staff member belongs to
	GroupIds *[]openapi_types.UUID `json:"groupIds,omitempty"`

	// HousingGroupId ID of the housing group this staff member belongs to (auto-populated from groupIds)
	HousingGroupId *openapi_types.UUID `json:"housingGroupId,omitempty"`
	Phone          *string             `json:"phone,omitempty"`

	// RoleId ID of the role this staff member has
	RoleId openapi_types.UUID `json:"roleId"`
}

// StaffMemberUpdateRequest defines model for StaffMemberUpdateRequest.
type StaffMemberUpdateRequest struct {
	Meta EntityCreationRequestMeta `json:"meta"`
	Spec StaffMemberMutationSpec   `json:"spec"`
}

// StaffMembersListResponse defines model for StaffMembersListResponse.
type StaffMembersListResponse struct {
	Items []StaffMember `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	// Id Unique identifier for the tenant
	Id string `json:"id"`

	// Name Tenant name
	Name string `json:"name"`
}

// TenantsListResponse defines model for TenantsListResponse.
type TenantsListResponse struct {
	Items []Tenant `json:"items"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Next Next offset value to use for the next page, or null if no more pages available
	Next *int `json:"next"`

	// Offset Current offset (starting position)
	Offset int `json:"offset"`

	// Total Total count of all items across all pages
	Total int `json:"total"`
}

// User defines model for User.
type User struct {
	// AccessRules Array of access rules defining user's permissions
	AccessRules []AccessRule `json:"accessRules"`

	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Id Unique identifier for the user
	Id string `json:"id"`

	// TenantId The tenant this user belongs to
	TenantId string `json:"tenantId"`
}

// AreasFilterBy defines model for AreasFilterBy.
type AreasFilterBy = []string

// AreasSortBy defines model for AreasSortBy.
type AreasSortBy string

// CampersFilterBy defines model for CampersFilterBy.
type CampersFilterBy = []string

// CampersSortBy defines model for CampersSortBy.
type CampersSortBy string

// CampsFilterBy defines model for CampsFilterBy.
type CampsFilterBy = []string

// CampsSortBy defines model for CampsSortBy.
type CampsSortBy string

// CertificationsFilterBy defines model for CertificationsFilterBy.
type CertificationsFilterBy = []string

// CertificationsSortBy defines model for CertificationsSortBy.
type CertificationsSortBy string

// ColorsFilterBy defines model for ColorsFilterBy.
type ColorsFilterBy = []string

// ColorsSortBy defines model for ColorsSortBy.
type ColorsSortBy string

// GroupsFilterBy defines model for GroupsFilterBy.
type GroupsFilterBy = []string

// GroupsSortBy defines model for GroupsSortBy.
type GroupsSortBy string

// HousingRoomsFilterBy defines model for HousingRoomsFilterBy.
type HousingRoomsFilterBy = []string

// HousingRoomsSortBy defines model for HousingRoomsSortBy.
type HousingRoomsSortBy string

// LocationsFilterBy defines model for LocationsFilterBy.
type LocationsFilterBy = []string

// LocationsSortBy defines model for LocationsSortBy.
type LocationsSortBy string

// RolesFilterBy defines model for RolesFilterBy.
type RolesFilterBy = []string

// RolesSortBy defines model for RolesSortBy.
type RolesSortBy string

// SessionsFilterBy defines model for SessionsFilterBy.
type SessionsFilterBy = []string

// SessionsSortBy defines model for SessionsSortBy.
type SessionsSortBy string

// StaffMembersFilterBy defines model for StaffMembersFilterBy.
type StaffMembersFilterBy = []string

// StaffMembersSortBy defines model for StaffMembersSortBy.
type StaffMembersSortBy string

// CampId defines model for camp_id.
type CampId = openapi_types.UUID

// Id defines model for id.
type Id = string

// Limit defines model for limit.
type Limit = int

// Offset defines model for offset.
type Offset = int

// Search defines model for search.
type Search = string

// SortOrder defines model for sortOrder.
type SortOrder string

// GetCampsParams defines parameters for GetCamps.
type GetCampsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *CampsFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *GetCampsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *GetCampsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// GetCampsParamsSortBy defines parameters for GetCamps.
type GetCampsParamsSortBy string

// GetCampsParamsSortOrder defines parameters for GetCamps.
type GetCampsParamsSortOrder string

// ListActivitiesParams defines parameters for ListActivities.
type ListActivitiesParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`
}

// ListAreasParams defines parameters for ListAreas.
type ListAreasParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *AreasFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListAreasParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListAreasParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListAreasParamsSortBy defines parameters for ListAreas.
type ListAreasParamsSortBy string

// ListAreasParamsSortOrder defines parameters for ListAreas.
type ListAreasParamsSortOrder string

// ListCampersParams defines parameters for ListCampers.
type ListCampersParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *CampersFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListCampersParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListCampersParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListCampersParamsSortBy defines parameters for ListCampers.
type ListCampersParamsSortBy string

// ListCampersParamsSortOrder defines parameters for ListCampers.
type ListCampersParamsSortOrder string

// ListCertificationsParams defines parameters for ListCertifications.
type ListCertificationsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *CertificationsFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListCertificationsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListCertificationsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListCertificationsParamsSortBy defines parameters for ListCertifications.
type ListCertificationsParamsSortBy string

// ListCertificationsParamsSortOrder defines parameters for ListCertifications.
type ListCertificationsParamsSortOrder string

// ListColorsParams defines parameters for ListColors.
type ListColorsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *ColorsFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListColorsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListColorsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListColorsParamsSortBy defines parameters for ListColors.
type ListColorsParamsSortBy string

// ListColorsParamsSortOrder defines parameters for ListColors.
type ListColorsParamsSortOrder string

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *GroupsFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListGroupsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListGroupsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListGroupsParamsSortBy defines parameters for ListGroups.
type ListGroupsParamsSortBy string

// ListGroupsParamsSortOrder defines parameters for ListGroups.
type ListGroupsParamsSortOrder string

// ListHousingRoomsParams defines parameters for ListHousingRooms.
type ListHousingRoomsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *HousingRoomsFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListHousingRoomsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListHousingRoomsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListHousingRoomsParamsSortBy defines parameters for ListHousingRooms.
type ListHousingRoomsParamsSortBy string

// ListHousingRoomsParamsSortOrder defines parameters for ListHousingRooms.
type ListHousingRoomsParamsSortOrder string

// ListLocationsParams defines parameters for ListLocations.
type ListLocationsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *LocationsFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListLocationsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListLocationsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListLocationsParamsSortBy defines parameters for ListLocations.
type ListLocationsParamsSortBy string

// ListLocationsParamsSortOrder defines parameters for ListLocations.
type ListLocationsParamsSortOrder string

// ListProgramsParams defines parameters for ListPrograms.
type ListProgramsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`
}

// ListRolesParams defines parameters for ListRoles.
type ListRolesParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *RolesFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListRolesParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListRolesParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListRolesParamsSortBy defines parameters for ListRoles.
type ListRolesParamsSortBy string

// ListRolesParamsSortOrder defines parameters for ListRoles.
type ListRolesParamsSortOrder string

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *SessionsFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListSessionsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListSessionsParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListSessionsParamsSortBy defines parameters for ListSessions.
type ListSessionsParamsSortBy string

// ListSessionsParamsSortOrder defines parameters for ListSessions.
type ListSessionsParamsSortOrder string

// ListStaffMembersParams defines parameters for ListStaffMembers.
type ListStaffMembersParams struct {
	// Limit Maximum number of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before starting to return results
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search term to filter items by name, title, or other text fields
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// FilterBy Filter results by parameters. Format: field operator value
	// Operators: == (equals), != (not equals), <= (less/equal), >= (greater/equal),
	// =@ (contains), !@ (not contains), =^ (starts with), =~ (ends with)
	// Dates in ISO 8601 format. Text filters are case-insensitive.
	// Note: Text operators (=@, !@, =^, =~) only work with text fields.
	FilterBy *StaffMembersFilterBy `form:"filterBy,omitempty" json:"filterBy,omitempty"`

	// SortBy Field name to sort by
	SortBy *ListStaffMembersParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortOrder Sort direction
	SortOrder *ListStaffMembersParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// ListStaffMembersParamsSortBy defines parameters for ListStaffMembers.
type ListStaffMembersParamsSortBy string

// ListStaffMembersParamsSortOrder defines parameters for ListStaffMembers.
type ListStaffMembersParamsSortOrder string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// CreateCampJSONRequestBody defines body for CreateCamp for application/json ContentType.
type CreateCampJSONRequestBody = CampCreationRequest

// CreateActivityJSONRequestBody defines body for CreateActivity for application/json ContentType.
type CreateActivityJSONRequestBody = ActivityCreationRequest

// UpdateActivityByIdJSONRequestBody defines body for UpdateActivityById for application/json ContentType.
type UpdateActivityByIdJSONRequestBody = ActivityUpdateRequest

// CreateAreaJSONRequestBody defines body for CreateArea for application/json ContentType.
type CreateAreaJSONRequestBody = AreaCreationRequest

// UpdateAreaByIdJSONRequestBody defines body for UpdateAreaById for application/json ContentType.
type UpdateAreaByIdJSONRequestBody = AreaUpdateRequest

// CreateCamperJSONRequestBody defines body for CreateCamper for application/json ContentType.
type CreateCamperJSONRequestBody = CamperCreationRequest

// UpdateCamperByIdJSONRequestBody defines body for UpdateCamperById for application/json ContentType.
type UpdateCamperByIdJSONRequestBody = CamperUpdateRequest

// CreateCertificationJSONRequestBody defines body for CreateCertification for application/json ContentType.
type CreateCertificationJSONRequestBody = CertificationCreationRequest

// UpdateCertificationByIdJSONRequestBody defines body for UpdateCertificationById for application/json ContentType.
type UpdateCertificationByIdJSONRequestBody = CertificationUpdateRequest

// CreateColorJSONRequestBody defines body for CreateColor for application/json ContentType.
type CreateColorJSONRequestBody = ColorCreationRequest

// UpdateColorByIdJSONRequestBody defines body for UpdateColorById for application/json ContentType.
type UpdateColorByIdJSONRequestBody = ColorUpdateRequest

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventCreationRequest

// UpdateEventByIdJSONRequestBody defines body for UpdateEventById for application/json ContentType.
type UpdateEventByIdJSONRequestBody = EventUpdateRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = GroupCreationRequest

// UpdateGroupByIdJSONRequestBody defines body for UpdateGroupById for application/json ContentType.
type UpdateGroupByIdJSONRequestBody = GroupUpdateRequest

// CreateHousingRoomJSONRequestBody defines body for CreateHousingRoom for application/json ContentType.
type CreateHousingRoomJSONRequestBody = HousingRoomCreationRequest

// UpdateHousingRoomByIdJSONRequestBody defines body for UpdateHousingRoomById for application/json ContentType.
type UpdateHousingRoomByIdJSONRequestBody = HousingRoomUpdateRequest

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = LocationCreationRequest

// UpdateLocationByIdJSONRequestBody defines body for UpdateLocationById for application/json ContentType.
type UpdateLocationByIdJSONRequestBody = LocationUpdateRequest

// CreateProgramJSONRequestBody defines body for CreateProgram for application/json ContentType.
type CreateProgramJSONRequestBody = ProgramCreationRequest

// UpdateProgramByIdJSONRequestBody defines body for UpdateProgramById for application/json ContentType.
type UpdateProgramByIdJSONRequestBody = ProgramUpdateRequest

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = RoleCreationRequest

// UpdateRoleByIdJSONRequestBody defines body for UpdateRoleById for application/json ContentType.
type UpdateRoleByIdJSONRequestBody = RoleUpdateRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = SessionCreationRequest

// UpdateSessionByIdJSONRequestBody defines body for UpdateSessionById for application/json ContentType.
type UpdateSessionByIdJSONRequestBody = SessionUpdateRequest

// CreateStaffMemberJSONRequestBody defines body for CreateStaffMember for application/json ContentType.
type CreateStaffMemberJSONRequestBody = StaffMemberCreationRequest

// UpdateStaffMemberByIdJSONRequestBody defines body for UpdateStaffMemberById for application/json ContentType.
type UpdateStaffMemberByIdJSONRequestBody = StaffMemberUpdateRequest

// UpdateCampByIdJSONRequestBody defines body for UpdateCampById for application/json ContentType.
type UpdateCampByIdJSONRequestBody = CampUpdateRequest
