# Configuration for generating Go client from OpenAPI spec
package: api
generate:
  client: true
  models: false
  embedded-spec: false
output-options:
  skip-prune: true
  response-type-suffix: "HTTPResponse"
compatibility:
  always-prefix-enum-values: true

