# Configuration for generating Go types from OpenAPI spec
package: api
generate:
  models: true
  embedded-spec: false
output-options:
  skip-prune: true
compatibility:
  always-prefix-enum-values: true

