# Configuration for generating Go server interfaces from OpenAPI spec
package: api
generate:
  chi-server: true
  embedded-spec: false
output-options:
  skip-prune: true
compatibility:
  always-prefix-enum-values: true

